default: &default
  adapter: postgresql
  encoding: unicode
  host: pg_db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: rails-cve-2017-17917_development

test:
  <<: *default
  database: rails-cve-2017-17917_test

production:
  <<: *default
  database: rails-cve-2017-17917_production
